--liquibase formatted sql;

--changeset flamierd:6;
CREATE TABLE IF NOT EXISTS authors
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(255)                            NOT NULL,
    lastname  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);
--rollback drop table if exists authors;

--changeset flamierd:7;
CREATE TABLE IF NOT EXISTS books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_books PRIMARY KEY (id)
);
--rollback drop table if exists books;

--changeset flamierd:8
CREATE TABLE IF NOT EXISTS books_authors
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_books_authors PRIMARY KEY (book_id, genre_id)
);
--rollback drop table if exists books_authors;

--changeset flamierd:9;
CREATE TABLE IF NOT EXISTS genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);
--rollback drop table if exists genres;

--changeset flamierd:10;
CREATE TABLE IF NOT EXISTS books_genres
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_books_genres PRIMARY KEY (book_id, genre_id)
);
--rollback drop table if exists books_genres;

--changeset flamierd:11;
ALTER TABLE books
    ADD CONSTRAINT uc_books_title UNIQUE (title);

ALTER TABLE genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);

ALTER TABLE books_authors
    ADD CONSTRAINT fk_booaut_on_author FOREIGN KEY (genre_id) REFERENCES authors (id);

ALTER TABLE books_authors
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE books_genres
    ADD CONSTRAINT fk_boogen_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE books_genres
    ADD CONSTRAINT fk_boogen_on_genre FOREIGN KEY (genre_id) REFERENCES genres (id);
--rollback alter table books drop constraint uc_books_title;
--rollback alter table genres drop constraint uc_genres_name;
--rollback alter table books_authors drop constraint fk_booaut_on_author;
--rollback alter table books_authors drop constraint fk_booaut_on_book;
--rollback alter table books_genres drop constraint fk_boogen_on_book;
--rollback alter table books_genres drop constraint fk_boogen_on_genre;