--liquibase formatted sql;

--changeset flamierd:6;
CREATE TABLE IF NOT EXISTS books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_books PRIMARY KEY (id)
);
--rollback drop table if exists books;

--changeset flamierd:7;
CREATE TABLE IF NOT EXISTS book_authors
(
    book_id BIGINT NOT NULL,
    authors VARCHAR(255)
);
--rollback drop table if exists book_authors;

--changeset flamierd:8;
CREATE TABLE IF NOT EXISTS book_genres
(
    book_id BIGINT NOT NULL,
    genres  VARCHAR(255)
);
--rollback drop table if exists book_genres;

--changeset flamierd:9;
ALTER TABLE books
    ADD CONSTRAINT uc_books_title UNIQUE (title);

ALTER TABLE book_authors
    ADD CONSTRAINT fk_book_authors_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_genres
    ADD CONSTRAINT fk_book_genres_on_book FOREIGN KEY (book_id) REFERENCES books (id);
--rollback alter table books drop constraint uc_books_title;
--rollback alter table book_authors drop constraint fk_book_authors_on_book;
--rollback alter table book_genres drop constraint fk_book_genres_on_book;
